# Classifiers Template

**Importing libraries**

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn import tree
from sklearn import ensemble
from sklearn import naive_bayes
from sklearn import neighbors
from sklearn import svm
from sklearn import metrics

**Loading the dataset**

In [2]:
df = pd.read_csv('Classifiers.csv')

In [3]:
df.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

## Setting up the data

**Train Test Split**

In [4]:
X = df[["Daily Time Spent on Site", "Age", "Area Income", "Daily Internet Usage", "Male"]].values
y = df["Clicked on Ad"].values

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Training models and Evaluating Model Performance

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Classifiers

In [7]:
classifiers = [
    ensemble.AdaBoostClassifier(n_estimators=300),
    ensemble.BaggingClassifier(n_estimators=300),
    ensemble.ExtraTreesClassifier(n_estimators=300),
    ensemble.GradientBoostingClassifier(n_estimators=300),
    ensemble.RandomForestClassifier(n_estimators=300),
    linear_model.PassiveAggressiveClassifier(),
    linear_model.RidgeClassifier(),
    linear_model.RidgeClassifierCV(),
    linear_model.SGDClassifier(),
    naive_bayes.BernoulliNB(),
    naive_bayes.GaussianNB(),
    neighbors.KNeighborsClassifier(),
    neighbors.NearestCentroid(),
    svm.LinearSVC(),
    svm.NuSVC(),
    svm.SVC(),
    tree.DecisionTreeClassifier(max_depth=3),
    tree.ExtraTreeClassifier(max_depth=3)
]

classification = pd.DataFrame(columns=['Classifier', 'Accuracy'], index=None)
for item in classifiers:
    print(item)
    clf = item
    clf.fit(X_train, y_train)
    predictions = clf.predict(X_test)
    classification = pd.concat([pd.DataFrame([[item, metrics.accuracy_score(y_test, predictions)]], columns=classification.columns, index=None), classification], ignore_index=True)
    print("Confusion Matrix: ")
    print(metrics.confusion_matrix(y_test, predictions))
    print("F1-Score: ", metrics.f1_score(y_test, predictions))
    print('Accuracy: ', metrics.accuracy_score(y_test, predictions))
    print('\n')

AdaBoostClassifier(n_estimators=300)
Confusion Matrix: 
[[ 80   9]
 [  9 102]]
F1-Score:  0.918918918918919
Accuracy:  0.91


BaggingClassifier(n_estimators=300)
Confusion Matrix: 
[[ 81   8]
 [  7 104]]
F1-Score:  0.9327354260089685
Accuracy:  0.925


ExtraTreesClassifier(n_estimators=300)
Confusion Matrix: 
[[ 84   5]
 [  8 103]]
F1-Score:  0.9406392694063928
Accuracy:  0.935


GradientBoostingClassifier(n_estimators=300)
Confusion Matrix: 
[[ 83   6]
 [  8 103]]
F1-Score:  0.9363636363636363
Accuracy:  0.93


RandomForestClassifier(n_estimators=300)
Confusion Matrix: 
[[ 84   5]
 [  8 103]]
F1-Score:  0.9406392694063928
Accuracy:  0.935


PassiveAggressiveClassifier()
Confusion Matrix: 
[[ 81   8]
 [  8 103]]
F1-Score:  0.9279279279279279
Accuracy:  0.92


RidgeClassifier()
Confusion Matrix: 
[[ 87   2]
 [ 10 101]]
F1-Score:  0.9439252336448598
Accuracy:  0.94


RidgeClassifierCV()
Confusion Matrix: 
[[ 87   2]
 [ 10 101]]
F1-Score:  0.9439252336448598
Accuracy:  0.94


SGDClassifie

In [8]:
classification[classification['Accuracy'] == classification['Accuracy'].max()]

Classifier  Accuracy
3    NuSVC()     0.955