# Classifiers Template

**Importing libraries**

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn import tree
from sklearn import ensemble
from sklearn import naive_bayes
from sklearn import neighbors
from sklearn import svm
from sklearn import metrics

**Loading the dataset**

In [2]:
df = pd.read_csv('Classifiers.csv')

In [3]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

## Setting up the data

**Train Test Split**

In [4]:
X = df[["Age","EstimatedSalary"]].values
y = df["Purchased"].values

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Training models and Evaluating Model Performance

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Classifiers

In [7]:
classifiers = [
    ensemble.AdaBoostClassifier(n_estimators=300),
    ensemble.BaggingClassifier(n_estimators=300),
    ensemble.ExtraTreesClassifier(n_estimators=300),
    ensemble.GradientBoostingClassifier(n_estimators=300),
    ensemble.RandomForestClassifier(n_estimators=300),
    linear_model.PassiveAggressiveClassifier(),
    linear_model.RidgeClassifier(),
    linear_model.RidgeClassifierCV(),
    linear_model.SGDClassifier(),
    naive_bayes.BernoulliNB(),
    naive_bayes.GaussianNB(),
    neighbors.KNeighborsClassifier(),
    neighbors.NearestCentroid(),
    svm.LinearSVC(),
    svm.NuSVC(),
    svm.SVC(),
    tree.DecisionTreeClassifier(max_depth=3),
    tree.ExtraTreeClassifier(max_depth=3)
]

classification = pd.DataFrame(columns=['Classifier', 'Accuracy'], index=None)
for item in classifiers:
    print(item)
    clf = item
    clf.fit(X_train, y_train)
    predictions = clf.predict(X_test)
    classification = pd.concat([pd.DataFrame([[item, metrics.accuracy_score(y_test, predictions)]], columns=classification.columns, index=None), classification], ignore_index=True)
    print("Confusion Matrix: ")
    print(metrics.confusion_matrix(y_test, predictions))
    print("F1-Score: ", metrics.f1_score(y_test, predictions))
    print('Accuracy: ', metrics.accuracy_score(y_test, predictions))
    print('\n')

AdaBoostClassifier(n_estimators=300)
Confusion Matrix: 
[[49  3]
 [ 7 21]]
F1-Score:  0.8076923076923077
Accuracy:  0.875


BaggingClassifier(n_estimators=300)
Confusion Matrix: 
[[46  6]
 [ 4 24]]
F1-Score:  0.8275862068965518
Accuracy:  0.875


ExtraTreesClassifier(n_estimators=300)
Confusion Matrix: 
[[46  6]
 [ 4 24]]
F1-Score:  0.8275862068965518
Accuracy:  0.875


GradientBoostingClassifier(n_estimators=300)
Confusion Matrix: 
[[47  5]
 [ 4 24]]
F1-Score:  0.8421052631578947
Accuracy:  0.8875


RandomForestClassifier(n_estimators=300)
Confusion Matrix: 
[[46  6]
 [ 3 25]]
F1-Score:  0.8474576271186439
Accuracy:  0.8875


PassiveAggressiveClassifier()
Confusion Matrix: 
[[52  0]
 [11 17]]
F1-Score:  0.7555555555555554
Accuracy:  0.8625


RidgeClassifier()
Confusion Matrix: 
[[50  2]
 [ 9 19]]
F1-Score:  0.7755102040816326
Accuracy:  0.8625


RidgeClassifierCV()
Confusion Matrix: 
[[50  2]
 [ 9 19]]
F1-Score:  0.7755102040816326
Accuracy:  0.8625


SGDClassifier()
Confusion Matrix:

In [8]:
classification[classification['Accuracy'] == classification['Accuracy'].max()]

Classifier  Accuracy
7  GaussianNB()    0.9375